### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by h1eutran** [rbeatty1/track-my-books#4]
I am looking for something like this but I wondering how you deploy it?

**Comment by rbeatty1** [comment]
@GuillouTran Sorry, this is more of a personal project. I do have plans to eventually document how to implement the back-end structure. I'll be sure to give an update whenever I end up getting around to that if you'd like.

**Comment by h1eutran** [comment]
Please do! I  have been looking for similar application for a while and I am too lazy to develop one from scratch :)
